backend:
  name: auth0
  branch: main
  base_url: "https://dev-g6feglvxbjuo57p0.us.auth0.com" # ВАШ ДОМЕН AUTH0
  app_id: "bQXWN1Csmgi74PihzDJ6oS8ep5BWGrg7" # ВАШ CLIENT ID AUTH0

# Налаштування для завантаження зображень
media_folder: "images"
public_folder: "/images"

# Налаштування колекцій
collections:
  - name: "products_collection"
    label: "Управління Продуктами"
    
    # Конфігурація для редагування вмісту одного файлу - products.json
    files:
      - file: "products.json" 
        label: "Список Товарів"
        name: "products_list_file"
        
        # Оскільки products.json - це масив, ми використовуємо "list" для масиву
        fields:
          - label: "Товари"
            name: "items"
            widget: "list"
            # Ці поля відповідають структурі об'єкта у вашому products.json
            fields:
              - { label: "ID", name: "id", widget: "number", valueType: "int", required: true, hint: "Унікальний номер товару" }
              - { label: "Назва", name: "name", widget: "string", required: true }
              # Дозволяємо дробові числа для ціни
              - { label: "Ціна", name: "price", widget: "number", valueType: "float", required: true, step: 0.01 } 
              - { label: "Категорія", name: "category", widget: "string", required: true }
              # Дозволяє завантажувати файл зображення
              - { label: "Зображення", name: "image", widget: "image", required: true, allow_multiple: false }