name: Update Products

on:
  workflow_dispatch: # запуск вручну
  repository_dispatch: # запуск через API

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run update script
        run: node admin/updateProducts.js

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add products.js images/
          git commit -m "Update products"
          git push
